---
- name: Check if reboot is required
  shell: needs-restarting -r
  failed_when: false
  register: reboot_required
  changed_when: false
- when: updates.stdout_lines | length > 0 and reboot_required.rc != 0
  block:
    - name: Reboot the server if required
      shell: sleep 3 && /sbin/shutdown -r now "Reboot required for updated kernel." && sleep 3
      ignore_errors: true
      changed_when: false
      async: 1
      poll: 0
    - name: Wait for server to come back after reboot
      wait_for_connection:
        connect_timeout: 10
        timeout: 300
        delay: 60
        sleep: 5
      register: reboot_result
    - name: Reboot time
      debug:
        msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."
- name: System details
  debug: msg="{{ item }}"
  with_items:
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"
