---
- hosts: all
  ping: ~

  connection: paramiko
  vars:
    ansible_ssh_private_key_file: /path/to/private_key
    ansible_ssh_pass: passphrase_for_private_key
  tasks:
    - debug:
        msg: hello
