---
- hosts: all
- name: Ping hosts
  ping: ~

- name: Copy ssh-key on hosts
  connection: paramiko
  vars:
    ansible_ssh_private_key_file: /home/{{current_user}}/.ssh/id_rsa
    ansible_ssh_pass: passphrase_for_private_key
  tasks:
    - debug:
        msg: " Data type of IP is {{ ansible_all_ipv4_addresses | type_debug }} "

- name: Check release vrsions
  shell: grep DISTRIB_RELEASE /etc/lsb-release
