---
- hosts: all
- name: Ping hosts
  ping: ~

- name: Copy ssh-key on hosts
  connection: paramiko
  vars:
    ansible_ssh_private_key_file: /path/to/private_key
    ansible_ssh_pass: passphrase_for_private_key
  tasks:
    - debug:
        msg: hello

- name: Check release vrsions
  shell: grep DISTRIB_RELEASE /etc/lsb-release
