---
- name: Ping hosts
  hosts: all
  tasks:
    - ping: ~

- name: Create user and copy ssh-key on hosts
  hosts: all
  tasks:
    - user:
        name: "{{ user }}"
        password: "{{ password }}"
        groups: wheel
        append: yes
        shell: "/bin/bash"
        state: present
    - lineinfile:
        path: "/etc/sudoers.d/{{ user }}"
        line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
    - authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '{{ keyfile }}') }}"

- name: OS information
  hosts: all
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
