---
- name: Ping hosts
  hosts: all
  tasks:
    - ping: ~

- name: Copy ssh-key on hosts
  hosts: all
  tasks:
    - authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '{{ keyfile }}') }}"

- name: OS information
  hosts: all
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
