---
- name: Performing yum update on localhost
  hosts: localhost
  become: yes
  gather_facts: true
  any_errors_fatal: false
  #########################################################
  # Execute update procedures
  #########################################################
  roles:
    - update

- name: Performing yum update on host(s)
  hosts: first
  become: yes
  any_errors_fatal: false
  #########################################################
  # Execute update procedures
  #########################################################
  roles:
    - update
    - reboot
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"

- name: Performing yum update on host(s)
  hosts: second
  become: yes
  any_errors_fatal: false
  #########################################################
  # Execute update procedures
  #########################################################
  roles:
    - update
    - reboot
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"

- name: Performing yum update on host(s) not reboot
  hosts: noreboot
  become: yes
  any_errors_fatal: false
  #########################################################
  # Execute update procedures
  #########################################################
  roles:
    - update
